# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1433422482);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1433422602);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1433268582);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"31.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.7.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1432850421000,\"rdfTime\":1431343267000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1431343970000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1431343576000}}}]");
user_pref("extensions.lastAppVersion", "31.7.0");
user_pref("extensions.lastPlatformVersion", "31.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("idle.lastDailyNotification", 1433422499);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.archive_folder", "mailbox://nobody@Local%20Folders/Archives");
user_pref("mail.identity.id1.compose_html", false);
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "mailbox://nobody@Local%20Folders/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "mailbox://nobody@Local%20Folders/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Gueugnaut Andrea");
user_pref("mail.identity.id1.htmlSigText", "-- \nAndrea Gueugnaut - gueugn_a\nING1 2017");
user_pref("mail.identity.id1.stationery_folder", "mailbox://nobody@Local%20Folders/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "gueugn_a@epita.fr");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.newsrc_root", "/home/inad/.thunderbird/u9z1nwmn.default/News");
user_pref("mail.newsrc_root-rel", "[ProfD]News");
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.purge_threshold_migrated", true);
user_pref("mail.root.nntp", "/home/inad/.thunderbird/u9z1nwmn.default/News");
user_pref("mail.root.nntp-rel", "[ProfD]News");
user_pref("mail.root.none", "/home/inad/.thunderbird/u9z1nwmn.default/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.directory", "/home/inad/.thunderbird/u9z1nwmn.default/Mail/Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.name", "Local Folders");
user_pref("mail.server.server1.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.charset", "ISO-8859-1");
user_pref("mail.server.server2.directory", "/home/inad/.thunderbird/u9z1nwmn.default/News/news.epita.fr");
user_pref("mail.server.server2.directory-rel", "[ProfD]News/news.epita.fr");
user_pref("mail.server.server2.hostname", "news.epita.fr");
user_pref("mail.server.server2.max_cached_connections", 2);
user_pref("mail.server.server2.newsrc.file", "/home/inad/.thunderbird/u9z1nwmn.default/News/newsrc-news.epita.fr");
user_pref("mail.server.server2.newsrc.file-rel", "[ProfD]News/newsrc-news.epita.fr");
user_pref("mail.server.server2.spamActionTargetAccount", "news://news.epita.fr");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "nntp");
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "bf08e618-cf95-4919-be1a-3785c0a969a");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "31.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1433422499);
user_pref("places.history.expiration.transient_current_max_pages", 100670);
user_pref("plugin.importedState", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1431433956);
user_pref("toolkit.telemetry.previousBuildID", "20150511105030");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
